### ISSUE TITLE
elementexplorer.js crashes for any input

### ISSUE THREAD

**Issue by Yukonjess101** [angular/protractor#1822]
I just updated to 1.7 and noticed anytime I attempt to input anything into the element explorer, the session closes:

![error](https://cloud.githubusercontent.com/assets/9010960/6236906/0a48633a-b6b4-11e4-95b3-a3dffcb17c7a.png)

I'm running this on:
Win 8.1 X64
Node:  v0.10.33
NPM:  1.4.28

This seems to happen regardless on how I run the element explorer, either by calling the flag "protractor --elementExplorer" or by going to the npm folder and launching it via node.  

Has anyone else seen this after the 1.7 update?

I'm going to roll back to 1.6.1, I know it is working normally there.

Thanks!

**Comment by juliemr** [comment]
Possibly a windows issue? Can anyone else confirm?

**Comment by subhash85** [comment]
yes i have also faced the same issue on my windows box after updating to 1.7

**Comment by sipanda84** [comment]
Yes I'm getting the same issue as well. Reverted back to Ptor 1.6.1 works

**Comment by hankduan** [comment]
I have a theory on why this is failing, but I have no windows machine to test this one (it's a little hard to debug when I can't try anything =P )

Anyway, here's my theory:
Currently protractor uses repl, and breakpoints, to run commands. (https://github.com/angular/protractor/blob/master/lib/debugger/clients/explorer.js#L28). I think the target might not be resolving properly on windows.

**Comment by sipanda84** [comment]
That works after changing ``` target: '.*executors\.js' ``` in ``` explorer.js ``` and ``` wddebugger.js ```. However there's a noticeable 30 seconds to a minute delay for elementExplorer to perform something (I've tested it on sendKeys() and exiting elementExplorer). Invoking elementExplorer from Node or Protractor seems to have similar issue. Does anyone else have the same issue or is it just me?

**Comment by hankduan** [comment]
Thanks @sipanda84 I've submitted a PR here https://github.com/angular/protractor/pull/1850 to address this. Waiting for someone to confirm the latency issue (@sipanda84, the latency isn't there when you use 1.6.1 right?)

**Comment by sipanda84** [comment]
I just switched back to 1.6.1 and confirmed no latency. 
Please note when I run elementExplorer on 1.6.1, I usually do ```webdriver-manager start``` first to initiate selenium server and on separate cmd prompt I do ```node elementexplorer.js http://xxxxx```. With Ptor 1.7.1 doing ```node elementexplorer.js http://xxxxx``` seems to automatically initiate the selenium server so I didn't have to do ```webdriver-manager start``` again. Not sure if the way I did it causes the latency issue.

**Comment by hankduan** [comment]
It shouldn't, but fyi:
node elementexplorer.js http://xxxxx
is equivalent to 
node elementexplorer.js http://xxxxx --seleniumAddress http://localhost:4444/wd/hub

**Comment by thinkjones** [comment]
I noticed severe latency issues when updating, plus hangs a lot.  1.6.1 was great.  Same for directConnect mode.  Plus I get lots of these type errors "TypeError: Converting circular structure to JSON", with statements that previously worked.

**Comment by hankduan** [comment]
Alright, there are two issues at hand here. One is "Converting circular structure to JSON". That's when there are circular references in the response. I will address that soon.

The second (and more problematic imo) is the latency. I just spent the whole day trying to figure out what is wrong with that, and have *just* figured it out. See https://github.com/joyent/node/issues/9319. So, let's wait and see what joyent says about that issue.

Meanwhile, sorry about the issues. You can downgrade to 1.6.1 for now, or I believe if you just copy the element explorer binary from 1.6.1 to 1.7.0, it should work as well. 

by the way: @thinkjones can you let me know what environment you are running this under? So far I think the latency issue is Windows and Ubuntu (as my Mac which I develop with suffers no such issue, and that why I haven't noticed this until now).

**Comment by thinkjones** [comment]
@hankduan Thanks for the awesomely quick response!  Mac here too.  Will downgrade and wait.

**Comment by hankduan** [comment]
Ok this issue is too overloaded. I'm going to break it up.

Issue 1) Cannot start element explorer on windows
  Already addressed in https://github.com/angular/protractor/pull/1850

Issue 2) "Converting circular structure to JSON"
  I created a PR to address this and should be fixed soon: https://github.com/angular/protractor/pull/1889

Issue 3) latency issue
  I'm going to track it in this issue: https://github.com/angular/protractor/issues/1890

Please comment in the corresponding issue/PR. Thanks!

**Comment by juliemr** [comment]
I believe this has all been addressed now. I'm going to close - if we're still seeing issues after the next release, let's open a fresh issue.

**Comment by chrisjlee** [comment]
I'm still having this particular issue. When a command returns json it decides to crash.

protractor version 2.4.0
