### ISSUE TITLE
Calling `pending` in a spec marks the spec as failed.

### ISSUE THREAD

**Issue by sveneh** [angular/protractor#2454]
See the attached testcase

https://gist.github.com/sveneh/9c589d321e6fc31f7460

When I run this in protractor@2.1.0 using jasmine@2.3.1 I get this:

```
>protractor pending.conf.js
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://192.168.88.100:60036/wd/hub
Started
F*

Failures:
1) a spec with pending should be pending
  Message:
    Failed: => marked PendingThis is pending.
  Stack:
    Error: Failed: => marked PendingThis is pending.
Pending:

1) a spec with pending should be also pending
  No reason given

2 specs, 1 failure, 1 pending spec
Finished in 0.006 seconds
Shutting down selenium standalone server.
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1
```

running the same spec in pure jasmine@2.3.1:
```
>jasmine 
Started
**

Pending:

1) a spec with pending should be pending
  This is pending.


2) a spec with pending should be also pending
  No reason given

2 specs, 0 failures, 2 pending specs
Finished in 0.002 seconds
```

Protractor should not fail specs that are marked as pending.

**Comment by cstraynor** [comment]
I'm experiencing this too. It would be good to get resolved so I can have accurate reports to delineate tests actually failing and tests being skipped.

**Comment by theandrewlane** [comment]
Someone please fix this!! In the meantime, to mark as pending without using ```pending("reason")``` use ```xit('some spec description', function (){```

**Comment by lynchblue** [comment]
+1 That's a pretty cool jasmine2 feature and it's a pity that we cannot use it with protractor. Is anyone taking care of this?

**Comment by ctapobep** [comment]
+1

**Comment by juliemr** [comment]
See https://github.com/angular/jasminewd/issues/27#issuecomment-144882283

**Comment by bruderol** [comment]
+1 this is really anoying! I want to be able to put tests to pending with correct messages in log.

**Comment by bruderol** [comment]
As a workaround I introduced an own pending to use in my protractor tests (overwriting the jasmine pending), maybe that is helpful for somebody else as a workaround:

```
            // in my protractor onPrepare code:
            var _pending = pending;
            pending = function(pendingMessage) {

                return {

                    it: function(description, itFunction) {
                        var consoleColorYellowStart = '\u001B[33m';
                        var consoleColorYellowEnd = '\u001B[0m';
                        return xit(description + '\n  ' + consoleColorYellowStart + 'Marked as Pending: ' + pendingMessage + consoleColorYellowEnd, itFunction);
                    },

                    describe: function(description, describeFunction) {
                        return describe(description, function() {
                            _pending(pendingMessage);
                            return describeFunction();
                        });
                    },

                    here: function() {
                        return _pending(pendingMessage);
                    }

                };

            };
```

Usage:
```pending('my pending comment').describe('my describe block', function() { ... });```
or
```pending('my pending comment').it('my it block', function() { ... });```
or (just in case you still need the old pure jasmine pending implementation somewhere else, with all advantages and disadvantages)
```pending('my pending comment').here();```

**Comment by ask1987** [comment]
+1

**Comment by lgarest** [comment]
Still experiencing this, meanwhile the workaround works like a charm @bruderol thanks!

**Comment by moneytree-doug** [comment]
Any updates on this issue?

**Comment by mattc41190** [comment]
Also feeling some burn here +1

**Comment by rcbop** [comment]
+1 also happening here. :(

**Comment by d-werner** [comment]
+1

**Comment by Fowowski** [comment]
+1

**Comment by bruderol** [comment]
In the meantime I found out that there is a possibility to set comments on tests ignored with `xit` and therefore even improved my workaround a little bit:

```
            // in my protractor onPrepare code:
            var _pending = pending;
            pending = function(pendingMessage) {

                return {

                    it: function(description, itFunction) {
                         var spec = xit(desription, itFunction);
                         spec.pend(pendingMessage);
                         return spec;                        
                    },

                    describe: function(description, describeFunction) {
                        return describe(description, function() {
                            _pending(pendingMessage);
                            return describeFunction();
                        });
                    },

                    here: function() {
                        return _pending(pendingMessage);
                    }

                };

            };
```

Usage:
```pending('my pending comment').describe('my describe block', function() { ... });```
or
```pending('my pending comment').it('my it block', function() { ... });```
or (just in case you still need the old pure jasmine pending implementation somewhere else, with all advantages and disadvantages)
```pending('my pending comment').here();```

**Comment by stheikki** [comment]
also experiencing this, is this issue currently being worked on?

**Comment by dverbovyi** [comment]
+ 1

**Comment by HugoDoyon** [comment]
+1 Should be priorize, this is a very usefull feature.

**Comment by juliemr** [comment]
Closing in favor of https://github.com/angular/jasminewd/issues/32

Note that this is pending a change to Jasmine.

**Comment by sgibson21** [comment]
I extended the jasmine-spec-reporter (https://www.npmjs.com/package/jasmine-spec-reporter)

```
var SpecReporter = require('jasmine-spec-reporter');
var PendingSpecReporter = SpecReporter;

PendingSpecReporter.prototype.specDone = function (spec) {
  this.metrics.stopSpec(spec);
  var pending = false;
  for(var i = 0; i < spec.failedExpectations.length; i++) {
    if ( spec.failedExpectations[i].message.toLowerCase().indexOf('pending') >= 0) pending = true;
  }
  if (spec.status === 'pending' || pending) {
    this.metrics.pendingSpecs++;
    this.display.pending(spec);
  } else if (spec.status === 'passed') {
    this.metrics.successfulSpecs++;
    this.display.successful(spec);
  } else if (spec.status === 'failed') {
    this.metrics.failedSpecs++;
    this.display.failed(spec);
  }
};

module.exports = PendingSpecReporter;
```

Specs marked as pending are displayed as pending in the report.

**Comment by andregs** [comment]
This hack works for me:
```js
// In protractor `onPrepare`
jasmine.Suite.prototype.pend = function (message) {
  this.markedPending = true;
  this.children.forEach(spec => spec.pend(message));
};
```

```js
xdescribe('Foo', function(){
  // bar
}).pend('reason');
```

**Comment by Sankannavar** [comment]
Am new to protractor
Was trying to skip some testcases on failure and continue remaining during batch run
I tried using pending but its not working inside it block
ex: 	it('Step 1:', function () {	
	});
	it('Step 1:', function () {
		if(true)
		{
			pending('my pending comment').it('my it block', function() {  });
		}
	});  here am getting as failed
 but same working outside of it block

it('Step 1:', function () {
		
	});
	
	pending('my pending comment').it('my it block', function() {  });

	it('Step 2:', function () {
		
	});
Please some one help me. thanks in advance.

**Comment by Kitsula** [comment]
Short workaround:
`(environment.postDeployment ? xit : it)('should something', () => {
    expect(true).toBeTruthy();
 });`

**Comment by aschlei** [comment]
This issue should be fixed in jasmine 2.9 (See https://github.com/jasmine/jasmine/commit/f4caf27). However, protractor is still using jasmine 2.8.

**Comment by ViieeS** [comment]
I have the latest version of Jasmine v3.3.0 and still get this behaviour... 😕

**Comment by tymfear** [comment]
> I have the latest version of Jasmine v3.3.0 and still get this behaviour... 😕

If you don't use Protractor 6.x, then, whichever version of Jasmine you got installed, you will use the version used by `jasminewd`.

**Comment by ViieeS** [comment]
@tymfear oh, sorry don't test it with protractor. It's about unit tests.

**Comment by nitin-kapoor** [comment]
I am using pending function like below but its marking as **failed**
Even the spec report treating pending function as failed.

![image](https://user-images.githubusercontent.com/34282001/85224998-b5fa7d00-b3eb-11ea-8374-92eb6eb0b5f3.png)

![image](https://user-images.githubusercontent.com/34282001/85224976-821f5780-b3eb-11ea-8825-4b97afeaf5a1.png)

**Comment by nitin-kapoor** [comment]
> I extended the jasmine-spec-reporter (https://www.npmjs.com/package/jasmine-spec-reporter)
> 
> ```
> var SpecReporter = require('jasmine-spec-reporter');
> var PendingSpecReporter = SpecReporter;
> 
> PendingSpecReporter.prototype.specDone = function (spec) {
>   this.metrics.stopSpec(spec);
>   var pending = false;
>   for(var i = 0; i < spec.failedExpectations.length; i++) {
>     if ( spec.failedExpectations[i].message.toLowerCase().indexOf('pending') >= 0) pending = true;
>   }
>   if (spec.status === 'pending' || pending) {
>     this.metrics.pendingSpecs++;
>     this.display.pending(spec);
>   } else if (spec.status === 'passed') {
>     this.metrics.successfulSpecs++;
>     this.display.successful(spec);
>   } else if (spec.status === 'failed') {
>     this.metrics.failedSpecs++;
>     this.display.failed(spec);
>   }
> };
> 
> module.exports = PendingSpecReporter;
> ```
> 
> Specs marked as pending are displayed as pending in the report.

Can you please help how to use this implementation in an angular project for e2e using protractor.

**Comment by Garcia-JuanLuis** [comment]
> 
> 
> This issue should be fixed in jasmine 2.9 (See [jasmine/jasmine@f4caf27](https://github.com/jasmine/jasmine/commit/f4caf27)). However, protractor is still using jasmine 2.8.

Hi, thank you for your support.  I've updated to Protractor 7.0.0 and Jasmine 3.6.3.
When I use **pending('Force skip')** ==> I get an error that says "**Failed: undefinedForce skip**".
NOTE: I also see a message that says "no tests were found" which is pretty interesting.

**Comment by Garcia-JuanLuis** [comment]
> 
> 
> > I extended the jasmine-spec-reporter (https://www.npmjs.com/package/jasmine-spec-reporter)
> > ```
> > var SpecReporter = require('jasmine-spec-reporter');
> > var PendingSpecReporter = SpecReporter;
> > 
> > PendingSpecReporter.prototype.specDone = function (spec) {
> >   this.metrics.stopSpec(spec);
> >   var pending = false;
> >   for(var i = 0; i < spec.failedExpectations.length; i++) {
> >     if ( spec.failedExpectations[i].message.toLowerCase().indexOf('pending') >= 0) pending = true;
> >   }
> >   if (spec.status === 'pending' || pending) {
> >     this.metrics.pendingSpecs++;
> >     this.display.pending(spec);
> >   } else if (spec.status === 'passed') {
> >     this.metrics.successfulSpecs++;
> >     this.display.successful(spec);
> >   } else if (spec.status === 'failed') {
> >     this.metrics.failedSpecs++;
> >     this.display.failed(spec);
> >   }
> > };
> > 
> > module.exports = PendingSpecReporter;
> > ```
> > 
> > 
> > Specs marked as pending are displayed as pending in the report.
> 
> I have used this implementation and it's awesome!
> But the issue is that even if we are using a pending function in the spec then jasmine is marking its status as failed only. I got to know while debugging(screenshot below) However I can add a little hack in this by adding checks for specific test cases by checking its description or id but this can cause issues later.
> 
> Can you please suggest something.
> 
> ![image](https://user-images.githubusercontent.com/34282001/85225749-f6a8c500-b3f0-11ea-89d8-ee6a9f5bb964.png)
> 
> **Test case shich is marked as pending**
> ![image](https://user-images.githubusercontent.com/34282001/85224998-b5fa7d00-b3eb-11ea-8374-92eb6eb0b5f3.png)



> 
> 
> I extended the jasmine-spec-reporter (https://www.npmjs.com/package/jasmine-spec-reporter)
> 
> ```
> var SpecReporter = require('jasmine-spec-reporter');
> var PendingSpecReporter = SpecReporter;
> 
> PendingSpecReporter.prototype.specDone = function (spec) {
>   this.metrics.stopSpec(spec);
>   var pending = false;
>   for(var i = 0; i < spec.failedExpectations.length; i++) {
>     if ( spec.failedExpectations[i].message.toLowerCase().indexOf('pending') >= 0) pending = true;
>   }
>   if (spec.status === 'pending' || pending) {
>     this.metrics.pendingSpecs++;
>     this.display.pending(spec);
>   } else if (spec.status === 'passed') {
>     this.metrics.successfulSpecs++;
>     this.display.successful(spec);
>   } else if (spec.status === 'failed') {
>     this.metrics.failedSpecs++;
>     this.display.failed(spec);
>   }
> };
> 
> module.exports = PendingSpecReporter;
> ```
> 
> Specs marked as pending are displayed as pending in the report.

This does not work for me; however, it could be the way I'm implementing it.
Would you place this code in its own class and then import it as a reporter?

I put the code under the Protractor config file, "onPrepare()" function... and I am getting two "results" in one window.

Failures:
1) Testing Skip Test shoud be skipped
  Message:
    Failed: => marked PendingSkipping This test
  Stack:
    Error: Failed: => marked PendingSkipping This test
        at C:\regUSA\Utilities\ProtractorTest\node_modules\jasminewd2\index.js:64:48
        at ControlFlow.emit (C:\regUSA\Utilities\ProtractorTest\node_modules\selenium-webdriver\lib\events.js:62:21)
        at ControlFlow.shutdown_ (C:\regUSA\Utilities\ProtractorTest\node_modules\selenium-webdriver\lib\promise.js:2674:10)
        at shutdownTask_.MicroTask (C:\regUSA\Utilities\ProtractorTest\node_modules\selenium-webdriver\lib\promise.js:2599:53)

1 spec, 1 failure
Finished in 0.012 seconds

**************************************************
*                    Pending                     *
**************************************************

1) Testing Skip Test shoud be skipped
  No reason given

Executed 0 of 1 spec INCOMPLETE (1 PENDING) in 0.012 sec.
[15:17:09] I/local - Shutting down selenium standalone server.
[15:17:09] I/launcher - 0 instance(s) of WebDriver still running
[15:17:09] I/launcher - chrome #01 failed 1 test(s)
[15:17:09] I/launcher - overall: 1 failed spec(s)
[15:17:09] E/launcher - Process exited with error code 1

**Comment by Garcia-JuanLuis** [comment]
I took the implementation provided by **sgibson21** and created a new project with Jasmine 3.6.3 and Protractor 7.0.0.
Still, I was getting failures when using **pending()**; so, I went ahead and started to play around with the implementation.  Following is what my confi.js file looks like:
`// conf.js
let Jasmine2HtmlReporter = require('protractor-jasmine2-html-reporter');
	var SpecReporter = require('jasmine-spec-reporter').SpecReporter;
	
let htmlReporter = new Jasmine2HtmlReporter({
  savePath: 'reports',
  fileName: 'e2e-report',
  takeScreenshotsOnlyOnFailures: true,
  cleanDestination: false,
  fileNameDateSuffix: true
});

exports.config = {
  framework: 'jasmine',
  specs: ['spec.js'],
  
  onPrepare() {
	var PendingSpecReporter = SpecReporter;

	PendingSpecReporter.prototype.specDone = function (spec) {
	  this.metrics.stopSpec(spec);
	  var pending = false;
	  var pendingReason;
	  for(var i = 0; i < spec.failedExpectations.length; i++) {
		  var index = spec.failedExpectations[i].message.toLowerCase().indexOf('pending');
		if ( index >= 0){
			pendingReason = spec.failedExpectations[i].message.substring(index+7); // 7 = the length of the word "pending"
			pending = true;
		}
	  }
	  if (spec.status === 'pending' || pending) {
		this.metrics.pendingSpecs++;
		this.display.pending(spec);
		
		spec['failedExpectations'] = [];
		spec['passedExpectations'] = [];
		spec['status'] = 'pending';
		
		if(spec['pendingReason'] === 'undefined' || spec['pendingReason'] === ''){
			spec['pendingReason'] = pendingReason;
		}
		
	  } else if (spec.status === 'passed') {
		this.metrics.successfulSpecs++;
		this.display.successful(spec);
	  } else if (spec.status === 'failed') {
		this.metrics.failedSpecs++;
		this.display.failed(spec);
	  }
	};
	
	module.exports = PendingSpecReporter;
  
    jasmine.getEnv().addReporter(new PendingSpecReporter({ spec: { displayStacktrace: 'pretty' } }));
	    // Assign the test reporter to each running instance
    jasmine.getEnv().addReporter(htmlReporter);
	
	let jasmineReporter = require('jasmine-reporters');
    jasmine.getEnv().addReporter(new jasmineReporter.JUnitXmlReporter({
      consolidateAll: true,
      savePath: 'reports',
      filePrefix: 'e2e-report',
    }));
  }
}`

**Following is what my specs look like**
`// spec.js
describe('Testing custom results', function() {
  xit('shoud be skipped because we are using "x" in front of the spec', function() {
	 pending('Force skip');
	  expect(true).toBe(true);
  });
  
    it('shoud be skipped using custom implementation', function() {	 
	  expect(true).toBe(true);
	  pending('My custom pending reason!');
  });
  
  it('shoud pass!', function() {
	  expect(true).toBe(true);
  });
  
  it('shoud fail!', function() {
	  expect(true).toBe(false);
  });
  
});`

**Following is what the XML report looks like**
`<?xml version="1.0" encoding="UTF-8"?>

-<testsuites disabled="0" time="0.028" tests="4" failures="1" errors="0">


-<testsuite disabled="0" time="0.028" tests="4" failures="1" errors="0" skipped="2" hostname="localhost" timestamp="2020-12-15T11:14:49" name="Testing custom results">


-<testcase time="0.001" name="shoud be skipped because we are using "x" in front of the spec" classname="Testing custom results">

<skipped message="Temporarily disabled with xit"/>

</testcase>


-<testcase time="0.004" name="shoud be skipped using custom implementation" classname="Testing custom results">

<skipped message="My custom pending reason!"/>

</testcase>

<testcase time="0.002" name="shoud pass!" classname="Testing custom results"/>


-<testcase time="0.018" name="shoud fail!" classname="Testing custom results">


-<failure message="Expected true to be false." type="toBe">

-<![CDATA[Error: Failed expectation
    at UserContext.<anonymous> (C:\regUSA\Utilities\ProtractorTest\spec.js:18:17)
    at C:\regUSA\Utilities\ProtractorTest\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\regUSA\Utilities\ProtractorTest\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\regUSA\Utilities\ProtractorTest\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\regUSA\Utilities\ProtractorTest\node_modules\jasminewd2\index.js:95:18)
    at TaskQueue.execute_ (C:\regUSA\Utilities\ProtractorTest\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\regUSA\Utilities\ProtractorTest\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at asyncRun (C:\regUSA\Utilities\ProtractorTest\node_modules\selenium-webdriver\lib\promise.js:2974:25)
    at C:\regUSA\Utilities\ProtractorTest\node_modules\selenium-webdriver\lib\promise.js:668:7]]>
</failure>

</testcase>

</testsuite>

</testsuites>`

**Following is what the HTML report looks like**
``
![image](https://user-images.githubusercontent.com/16019041/102242494-1b758500-3ec8-11eb-9770-c86e9e86e06b.png)

**Comment by shadiabuhilal** [comment]
To skip test block programmatically, please use `done` arg, and call `done` function before calling `pending`.

example:
```
it('promise pends', function(done) {
  return new Promise(function () {
    // Make sure to call done() before pending()
    done();
    pending('promise');
  });
});
```
