### ISSUE TITLE
[Question] Is Protractor capable of loading a config file written in ES6?

### ISSUE THREAD

**Issue by rolandjitsu** [angular/protractor#2732]
I was trying to load a config file written in ES6 but it looks like that doesn't work:
```shell
ERROR - failed loading configuration file protractor.config.js
/Users/rolandjitsu/Projects/ng2-lab/protractor.config.js:1
(function (exports, require, module, __filename, __dirname) { import yargs from 'yargs';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at ConfigParser.addFileConfig (/Users/rolandjitsu/Projects/ng2-lab/node_modules/protractor/lib/configParser.js:175:22)
    at Object.init (/Users/rolandjitsu/Projects/ng2-lab/node_modules/protractor/lib/launcher.js:103:18)
    at Object.<anonymous> (/Users/rolandjitsu/Projects/ng2-lab/node_modules/protractor/lib/cli.js:139:23)
```
Is this possible or not? I have karma running the same way and it seems to work.
**Note**: I am running node 5 and protractor 3.

**Comment by jairovsky** [comment]
Node hasn't fully implemented ES6 modules yet, that's why you can't **`import`** modules.

More info: https://nodejs.org/en/docs/es6/

**Comment by rolandjitsu** [comment]
That is true:
```shell
  --harmony_modules (enable "harmony modules" (in progress))
  --harmony_regexps (enable "harmony regular expression extensions" (in progress))
  --harmony_proxies (enable "harmony proxies" (in progress))
  --harmony_sloppy_function (enable "harmony sloppy function block scoping" (in progress))
  --harmony_sloppy_let (enable "harmony let in sloppy mode" (in progress))
  --harmony_unicode_regexps (enable "harmony unicode regexps" (in progress))
  --harmony_reflect (enable "harmony Reflect API" (in progress))
  --harmony_destructuring (enable "harmony destructuring" (in progress))
  --harmony_default_parameters (enable "harmony default parameters" (in progress))
  --harmony_sharedarraybuffer (enable "harmony sharedarraybuffer" (in progress))
  --harmony_atomics (enable "harmony atomics" (in progress))
  --harmony_simd (enable "harmony simd" (in progress))
```
But it is odd that Karma can run the config file without problems, but not protractor, that is why I asked. I guess if I run node with `--harmony` flag, should fix the issue for now until they fully implement the feature.

**Comment by sjelin** [comment]
It is odd that karma can run the file while protractor can't.  This is still an issue with node though so I'm going to close it
