### ISSUE TITLE
Unable to send the ENTER key command to input fields

### ISSUE THREAD

**Issue by Jadezone** [angular/protractor#3456]
I'm testing an Angular 2 website, I cannot send the enter key command to any inputs throughout the website. When running the tests, they pass, however, when watching the test run, it does not actually send the enter command. 
I think it may be an issue with the input element as it works with other elements.
I've tried multiple ways of sending the key command but I've always used: `.sendKeys(protractor.Key.ENTER);`
- Node Version: `4.4.2`
- Protractor Version: `3.3.0`
- Browser(s): `Chrome/Firefox`
- Operating System and Version `Windows 10`
- Protractor configuration file: 

``` javascript
exports.config = {

    framework: 'jasmine',
    useAllAngular2AppRoots: true,
    seleniumAddress: 'http://127.0.0.1:4444/wd/hub',
    specs: ['*e2e-spec.js'],
    capabilities: {
        browserName: 'firefox'
    }
};
```
- Example test:

``` javascript
 it('Should display an error when there is no name name entered', function () {
        newName.newNameButton.click();
        newName.enterName.click();
        newName.enterName.sendKeys(protractor.Key.ENTER);
        newName.errorMessage.isDisplayed().then(function (isDisplay) {
            expect(isDisplay).toBe(true);
        });
    });
```
- Element in the page objects:

``` javascript
this.enterName = element(by.id("nameInput"));
```
- HTML snippet:

``` html
            <div class="addNameDialogue__form" _ngcontent-mpw-5="">
                <div class="animated-input-group" _ngcontent-mpw-5="">
                    <input id="nameInput" class="modal-input ng-pristine ng-valid ng-touched" _ngcontent-mpw-5="" type="text">
                    <label for="nameInput" _ngcontent-mpw-5="">New name</label>
                </div>
            </div>
            <div class="addNameDialogue__infoAlert" _ngcontent-mpw-5="">
                <!--template bindings={}-->
                <!--template bindings={}--><span class="addNameDialogue__infoAlert-alertText" _ngcontent-mpw-5="">This new name will be added</span>
            </div>
```
- Output from running the test: 
  Enter key is not actually submitted but test passes 
  (Escape key does not work either)

**Comment by Emilemuny** [comment]
Test passes? doesn't that mean you met your expectation newName.errorMessage.isDisplayed() after Enter key submit, Looks to me it is working fine!  How about you try to fail your test with newName.enterName.sendKeys('testname', protractor.Key.ENTER)

**Comment by JadeSudell** [comment]
Apologies, I mentioned the test passing because there is no console error that I can provide about the Enter key not submitting (the test can still see the element displayed as it's always in the DOM). 
I can physically see that it is not getting submitted properly and in other circumstances it should dismiss the modal.

**Comment by Jadezone** [comment]
Apologies, I mentioned the test passing because there is no console error that I can provide about the Enter key not submitting (the test can still see the element displayed as it's always in the DOM). 
I can physically see that it is not getting submitted properly and in other circumstances it should dismiss the modal.

**Comment by sjelin** [comment]
1. How do you know the test isn't just closing out very quickly after the enter key is sent?
2. Could you change your error message check at the end to:

```js
        expect(newName.errorMessage.isDisplayed()).toBe(true);
```

Protractor automatically unwraps the promise, and this way it will know to wait before killing the test process

**Comment by Jadezone** [comment]
@sjelin 1) I have added browser.sleep(5000); after the sendKeys to watch the test running visually and the modal does not respond to the key sent.
2) I have tried changing the assertion as per your suggestion, but the test still closes and passes with no reaction.

As I mentioned earlier the assertion is unrelated as the element is always in the dom(not displayed to the user), the input is still not responding to the enter key.

If I send the key to the parent element(found by .animated-input-group), I am able to see the element respond to the enter key (focus changes), however, when sending the key press to the <input>, it does not respond.

**Comment by Emilemuny** [comment]
@Jadezone, can you try to send an empty string, like newName.enterName.sendKeys('',protractor.Key.ENTER);
I would also recommend using elementExplorer to interactively debug the issue at that specific point where it fails.

**Comment by cnishina** [comment]
Related closed issue: https://github.com/angular/protractor/issues/3530

**Comment by Jadezone** [comment]
@Emilemuny I attempted to send an empty string to the input and still no luck. 
I also tried sending the enter key to an existing Angular 2 site and it worked as expected, so I'm not sure if this is something related to the way our website is built or due to the chrome version as referenced in #3530

**Comment by juliemr** [comment]
I think this is due to https://bugs.chromium.org/p/chromedriver/issues/detail?id=1411

The good news is that this should be fixed in the next chromedriver release.

**Comment by juliemr** [comment]
This is now fixed in the released chromedriver. Yay!

**Comment by vivacenontroppo** [comment]
Still can't figure it out. Can someone help me? I'm using this method in my page object (RETURN, instead of ENTER, it suppose to work in firefox):
```
public clickEnter = (): promise.Promise<void> =>
        browser
            .actions() 
            .sendKeys(protractor.Key.RETURN)
            .perform()
```

and then I just invoke it in the test like `basePage.clickEnter();`,
but still i get:

```
Failed: sendKeysToActiveElement
    Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
    System info: host: 'mbp-marian.home', ip: 'fe80:0:0:0:cc4:9718:d972:3952%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '10.0.2'
    Driver info: driver.version: unknown
```
