### ISSUE TITLE
Double output on failures in hooks using Protractor & Mocha

### ISSUE THREAD

**Issue by eswets** [angular/protractor#4192]
When using Mocha and Protractor, if an error occurs (i.e. AssertionError) inside a hook, output is printed twice.

When using Mocha without Protractor, this behaviour does not occur.

### To reproduce:

Clone https://github.com/eswets/mocha-double-output

**To run with Protractor:**
Run `npm install`, `npm run update-webdriver-dependencies`, `npm run protractor`

**Produces output:**
```
[16:24:35] I/launcher - Running 1 instances of WebDriver
[16:24:36] I/direct - Using ChromeDriver directly...


  Some spec
    1) "before all" hook: Failing before

  0 passing (10ms)
  1 failing

  1) Some spec "before all" hook: Failing before:

      AssertionError: expected true to equal false
      + expected - actual

      -true
      +false
      
      at Context.<anonymous> (someSpec.js:6:25)
      at runTest (node_modules/selenium-webdriver/testing/index.js:166:22)
      at node_modules/selenium-webdriver/testing/index.js:187:16
      at new ManagedPromise (node_modules/selenium-webdriver/lib/promise.js:1067:7)
      at controlFlowExecute (node_modules/selenium-webdriver/testing/index.js:186:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2970:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2953:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2860:25)
      at node_modules/selenium-webdriver/lib/promise.js:676:7
  From: Task: Some spec "before all" hook: Failing before
      at Context.ret (node_modules/selenium-webdriver/testing/index.js:185:10)





  0 passing (16ms)
  1 failing

  1) Some spec "before all" hook: Failing before:

      AssertionError: expected true to equal false
      + expected - actual

      -true
      +false
      
      at Context.<anonymous> (someSpec.js:6:25)
      at runTest (node_modules/selenium-webdriver/testing/index.js:166:22)
      at node_modules/selenium-webdriver/testing/index.js:187:16
      at new ManagedPromise (node_modules/selenium-webdriver/lib/promise.js:1067:7)
      at controlFlowExecute (node_modules/selenium-webdriver/testing/index.js:186:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2970:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2953:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2860:25)
      at node_modules/selenium-webdriver/lib/promise.js:676:7
  From: Task: Some spec "before all" hook: Failing before
      at Context.ret (node_modules/selenium-webdriver/testing/index.js:185:10)



[16:24:36] I/launcher - 0 instance(s) of WebDriver still running
[16:24:36] I/launcher - chrome #01 failed 1 test(s)
[16:24:36] I/launcher - overall: 1 failed spec(s)
[16:24:36] E/launcher - Process exited with error code 1
```

**To run only Mocha:**

`npm test`

**Produces output:**
```
Some spec
    1) "before all" hook: Failing before


  0 passing (8ms)
  1 failing

  1) Some spec "before all" hook: Failing before:

      AssertionError: expected true to equal false
      + expected - actual

      -true
      +false
      
      at Context.<anonymous> (someSpec.js:6:25)
```

Relevant misc information:
- Node Version: `6.9.4`
- Protractor Version: `5.1.1`
- Operating System and Version `MacOS Sierra 10.12.4`
- Protractor config:
```
exports.config = {
    specs: '*Spec.js',
    directConnect: true,
    maxSessions: 1,
    framework: 'mocha',
    mochaOpts: {
        reporter: 'spec',
        bail: true,
        colors: true,
    },
};
```

**Comment by eswets** [comment]
This behaviour seems to be caused by including the `bail: true` flag.

**Comment by wswebcreation** [comment]
@eswets 

Is this solved now for you? If so, can we close the issue?

**Comment by eswets** [comment]
Sorry for the late reply, but the issue still persists. Not using Mocha's `bail` functionality works around the issue, but this means losing out on the `bail` functionality (stop running a testsuite on a failure).

**Comment by wswebcreation** [comment]
Ok, sorry for closing. Will look into it the coming days
