### ISSUE TITLE
unexpected behaviour - Jasmine spec timeout issue 

### ISSUE THREAD

**Issue by TwinkleA** [angular/protractor#4397]
My jasmine specs work fine only with protractor version 4.0.3, The moment I update the protractor version the same scripts start failing with below error. 

Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

The angualar pages load properly and step executes successfully but, above error message is thrown on console when it moves to next step, 

![jamine1](https://user-images.githubusercontent.com/18376082/28458362-195afedc-6e27-11e7-90cf-76e641ec82c6.PNG)

![jasmine2](https://user-images.githubusercontent.com/18376082/28458383-2b1a332c-6e27-11e7-9d5a-7cfa3700fffe.PNG)

**Comment by wswebcreation** [comment]
If this is a bug, please use the form I've added into your issue. Also provide a example script we can use to debug your issue.

Tnx

**Comment by TwinkleA** [comment]
@wswebcreation - I found that the issue is with jasmine version. the above mentioned issue occurs with jasmine - "jasmine": "2.7.0" (wherein  jasminewd2 - 0.0.10 gets installed by default)
I updated package.json to use "jasmine": "2.6.0",  "jasminewd2": "^2.1.0", and it worked.

hence there is some issue with latest version of jasmine library

**Comment by wswebcreation** [comment]
Hi @TwinkleA ,

Is there still a problem now? Or can this be closed. By the way, there were some breaking changes in [protractor 5](https://github.com/angular/protractor/blob/master/CHANGELOG.md#500) that could have to do with your poroblem, hence the upgrade to version 5.0.0
