### ISSUE TITLE
visibilityOf/presenceOf/etc. gives opposite result for disabled inputs

### ISSUE THREAD

**Issue by JonWallsten** [angular/protractor#5198]
Bug report
---

- Node Version: `10.9.0`
- Protractor Version: `6.0.0`
- Angular Version: `7.2.10`
- Browser(s): `Chrome`
- Operating System and Version `Window 10`

When using expected conditions on a disabled input the following EC:s gives you `false` even though the element is really there (verified visually):
presenceOf
visibilityOf
elementToBeClickable

Also `textToBePresentInElementValue` doesn't match even though it shouldn't

Same code worked fine before upgrading.

**Comment by JonWallsten** [comment]
@cnishina: Would you mind take a look at this?

**Comment by JonWallsten** [comment]
@kyliau @alan-agius4 : I noticed you guys have started to make commits in this repo! That's awesome. When we did a POC to try to move to Protractor 6 this is what stopped us. Please take a look whenever you have the chance and thanks for you contributions.

**Comment by alan-agius4** [comment]
Hi @JonWallsten, protractor version 6, is deprecated.

Unless you are already on Protractor version 6 you shouldn’t try to use it.

**Comment by JonWallsten** [comment]
@alan-agius4 I'm aware. We did this POC last year. But I doubt this bug has been fixed since. Hence the mention on you guys. I can try to recreate the behavior in 7.x.x and update the bug. If I recall correctly this was the major thing stopping us from proceed with the await/async upgrade. I tried to figure out myself what was happening, but got lost in the Protractor source code.

**Comment by xiuzhen1103** [comment]
This is still an issue, I have experienced. It was working few weeks ago until I updated to latest protractor version 7.0.0

**Comment by peteboere** [comment]
As far as I'm aware this issue was with 6 due to a alpha version of selenium driver used. Protractor 7 uses the same stable selenium driver as 5.x and appears to be mainly a code clean-up

**Comment by xiuzhen1103** [comment]
I found root cause was test failed due to failed test when running multiple instance causing selector not found and second instance not opening  the page
